import type {
  GetStaticProps,
  GetServerSideProps,
  InferGetServerSidePropsType,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import Section from "../../components/Section";
import SectionTitle from "../../components/SectionTitle";
import { sanityClient } from "../../utils/sanity.server";
const Home: NextPage = (
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  const { resume } = props;
  const { person, jobs } = resume;
  // console.log({ person, jobs });
  return (
    <div>
      <Head>
        <title>{resume.person.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-2">
        <h1 className="max-w-3xl mx-auto flex flex-col mb-4   md:justify-center md:divide-x-4  md:flex-row   items-baseline ">
          <span className="text-5xl  font-semibold  text-slate-600 md:pr-2 ">
            {person.name}
          </span>
          <span className="text-5xl  font-semibold text-slate-500 md:pl-2">
            {resume.jobTitle}
          </span>
        </h1>

        <SectionTitle>Professional Experience</SectionTitle>

        {
          //Map out a list jobs with position, company and list of tasks
          resume.jobs.map((job: Job) => (
            <Section key={job.id}>
              <dl className="gap-y-1 md:gap-y-4 gap-x-2 grid grid-cols-1 sm:grid-cols-2">
                <dt className="sr-only">Company</dt>{" "}
                <dd className="font-semibold  col-span-2 sm:col-span-1 text-slate-700 text-lg md:text-xl">
                  {job.company}
                </dd>
                <dt className="sr-only">Position</dt>
                <dd className=" text-slate-800 col-span-2 sm:col-span-1 md:text-lg w-full flex sm:justify-end  ">
                  <div className="max-w-[65%%]">{job.position}</div>
                </dd>
                <dt className="sr-only">Highlights</dt>
                <dd className="col-span-2 text-sm text-slate-600 pl-2 md:pl-4">
                  <ul className=" md:pl-6  w-full pl-2 list-outside list-disc">
                    {job.tasks.map((task) => (
                      <li key={task.id}>
                        {task.description}
                        <ul className="list-[circle] pl-4 md:pl-6 list-outside">
                          {task.subtask &&
                            task.subtask.map((subTask, index) => (
                              <li key={index.toString()}>{subTask}</li>
                            ))}
                        </ul>
                      </li>
                    ))}
                  </ul>
                </dd>
              </dl>
            </Section>
          ))
        }

        <SectionTitle>Education</SectionTitle>

        <Section>
          <div className="flex justify-between">
            <span className=" text-slate-800 text-lg md:text-xl font-semibold">
              Western Governors University
            </span>
            <span className="text-slate-800 md:text-lg">
              B.S. Software Development 2018
            </span>
          </div>
        </Section>

        <SectionTitle>Volunteering</SectionTitle>
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const resume = await sanityClient.fetch(
    `*[_type == "resume" ]{...,  jobs[]->{...},person->}`
  );

  return { props: { resume: resume[0] ?? null } };
  // ...
};

//Get static props from the sanityClient
// export const getStaticProps: GetStaticProps = async (context) => {
//   const resume = await sanityClient.fetch(
//     `*[_type == "resume" ]{...,  jobs[]->{...},person->}`
//   );

//   return { props: { resume: resume[0] ?? null } };
//   // ...
// };

export default Home;
