import type {
  GetStaticProps,
  GetServerSideProps,
  InferGetServerSidePropsType,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import JobSection from "../../components/JobSection";
import Section from "../../components/Section";
import SectionTitle from "../../components/SectionTitle";
import { sanityClient } from "../../utils/sanity.server";
const Home: NextPage = (
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  const { resume } = props;
  const { person, sections } = resume;
  console.log({ resume });
  return (
    <div>
      <Head>
        <title>{resume.person?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-2">
        <h1 className="max-w-3xl mx-auto flex flex-col mb-4   md:justify-center md:divide-x-4  md:flex-row   items-baseline ">
          <span className="text-5xl  font-semibold  text-slate-600 md:pr-2 ">
            {person?.name}
          </span>
          <span className="text-5xl  font-semibold text-slate-500 md:pl-2">
            {resume?.jobTitle}
          </span>
        </h1>

        {sections &&
          sections.map((section: Section) => (
            <JobSection key={section.id} section={section} />
          ))}
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { query, params } = context;

  console.log({ query, params });
  const resume = await sanityClient.fetch(
    `*[_type == "resume" && name==$name  ]{..., sections[]->{...,jobs[]->{...}}  ,person->}`,
    { name: query.name ?? "Default" }
  );
  console.log({ resume });
  return { props: { resume: resume[0] ?? null } };
  // ...
};

//Get static props from the sanityClient
// export const getStaticProps: GetStaticProps = async (context) => {
//   const resume = await sanityClient.fetch(
//     `*[_type == "resume" ]{...,  jobs[]->{...},person->}`
//   );

//   return { props: { resume: resume[0] ?? null } };
//   // ...
// };

export default Home;
